// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3S6iOT2QcpZSqMRA0SBMvgCMAuXB4DZc',
    appId: '1:224306810903:web:7a251df86423e5e44ccc52',
    messagingSenderId: '224306810903',
    projectId: 'app-seneca-registros-bano-5e22',
    authDomain: 'app-seneca-registros-bano-5e22.firebaseapp.com',
    storageBucket: 'app-seneca-registros-bano-5e22.appspot.com',
    measurementId: 'G-GG5KMVMQR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnLsdk7Pq-rMU0-wguiiS64YW3yhO4Mtg',
    appId: '1:224306810903:android:e07d77e38d0a19194ccc52',
    messagingSenderId: '224306810903',
    projectId: 'app-seneca-registros-bano-5e22',
    storageBucket: 'app-seneca-registros-bano-5e22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-F_47HZpBUYSFuSNt5y7_APcKlxkI5f0',
    appId: '1:224306810903:ios:da44c26d8434aae14ccc52',
    messagingSenderId: '224306810903',
    projectId: 'app-seneca-registros-bano-5e22',
    storageBucket: 'app-seneca-registros-bano-5e22.appspot.com',
    iosClientId: '224306810903-3fd68spk87ndsq1t0cct41t568q9ku1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSenecaRegistrosBano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-F_47HZpBUYSFuSNt5y7_APcKlxkI5f0',
    appId: '1:224306810903:ios:622afaf23a7119244ccc52',
    messagingSenderId: '224306810903',
    projectId: 'app-seneca-registros-bano-5e22',
    storageBucket: 'app-seneca-registros-bano-5e22.appspot.com',
    iosClientId: '224306810903-v898t9m9ietec0pk831vljn2pbesgnob.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSenecaRegistrosBano.RunnerTests',
  );
}
